#!/bin/sh
# Download and install all Intel Hex firmware files from the Linux distribution to /usr/local/etc/midisport_firmware
echo "Downloading MIDISPORT Firmware archive"
curl --location --output /tmp/midisport_firmware.tar.gz https://downloads.sourceforge.net/project/usb-midi-fw/midisport-firmware/1.2/midisport-firmware-1.2.tar.gz
tar -C /tmp/ -x -z -f /tmp/midisport_firmware.tar.gz
echo "Installing MIDISPORT firmware files"
sudo mkdir -p /usr/local/etc/midisport_firmware/
sudo cp /tmp/midisport-firmware-1.2/*.ihx /usr/local/etc/midisport_firmware/
echo "Installed MIDISPORT firmware files"

# This script could be launched from anywhere, so we need to find the firmware extraction script,
# which will be in the same directory as this one.
$(dirname $0)/extractMAudioFirmware.sh

exit 0

