#!/bin/zsh
# Download and install all Intel Hex firmware files from the Linux distribution to /usr/local/etc/midisport_firmware
curl --location --output /tmp/midisport_firmware.tar.gz https://downloads.sourceforge.net/project/usb-midi-fw/midisport-firmware/1.2/midisport-firmware-1.2.tar.gz
tar -C /tmp/ -x -z -f /tmp/midisport_firmware.tar.gz
sudo mkdir -p /usr/local/etc/midisport_firmware/
sudo cp /tmp/midisport-firmware-1.2/*.ihx /usr/local/etc/midisport_firmware/

# TODO Install MIDISPORTFirmwareDownloader/MIDISPORT_devices.xml /usr/local/etc/
# TODO Install MIDISPORTFirmwareDownloader/com.leighsmith.midisportfirmwaredownloader.plist /Library/LaunchDaemons/


